# Generated by Django 5.2.4 on 2025-08-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_add_zip_to_address'),
    ]

    operations = [
        migrations.RunSQL('''
            INSERT INTO store_collection (title)
            VALUES ('collection1')
        ''', '''
            DELETE FROM store_collection
            WHERE title='collection1'
        ''')
    ]
